version: '3'
services:
  db:
   build: ./docker/mysql
   environment:
    MYSQL_ROOT_PASSWORD: admin123
    MYSQL_ROOT_HOST: '%'
   restart: always
  app:
    build: ./docker/java
    environment:
        title: Hand
        description: com.Hand
        language_id: 1
        db_ip: db
        db_port: 3306
        db_user: root
        db_pd: admin123


