spring:
    datasource:
        url: jdbc:mysql://${db_ip}:${db_port}/${db_name}?seUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
        username: ${db_user}
        password: ${db_pd}
        driver-class-name: ${driver}
    jpa:
        database: mysql
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        show-sql: false
        hibernate:
            ddl-auto: update
            format_sql: true
    context:
        listener:
            classes: com.hand.al.exam1.listener.MyListener